language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "python setup.py install"
  - "pip install -U pip"
  - "pip uninstall ua-parser --yes"
  - "pip install pyyaml ua-parser --no-use-wheel"
script:
  - python -m unittest discover
